version: "3.8"

x-app-environment: &appEnvironment
  APP_NAME: ${APP_NAME}
  APP_KEY: ${APP_KEY}
  APP_DEBUG: ${APP_DEBUG}
  APP_ENV: ${APP_ENV}
  DB_CONNECTION: ${DB_CONNECTION}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_DATABASE: ${DB_DATABASE}
  DB_USERNAME: ${DB_USER}
  DB_PASSWORD: ${DB_PASS}

networks:
  laravel:

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.prod.dockerfile
    ports:
      - "80:80"
      - "443:443"
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.prod.dockerfile
    environment:
      <<: [*appEnvironment]
