version: "3.8"

x-app-environment: &appEnvironment
  APP_NAME: ${APP_NAME}
  APP_KEY: ${APP_KEY}
  APP_DEBUG: ${APP_DEBUG}
  APP_ENV: ${APP_ENV}
  DB_CONNECTION: ${DB_CONNECTION}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_DATABASE: ${DB_DATABASE}
  DB_USERNAME: ${DB_USER}
  DB_PASSWORD: ${DB_PASS}

x-database-environment: &databaseEnvironment
  MYSQL_DATABASE: ${DB_DATABASE}
  MYSQL_USER: ${DB_USER}
  MYSQL_PASSWORD: ${DB_PASS}
  MYSQL_ROOT_PASSWORD: ${DB_PASS}
  SERVICE_TAGS: dev
  SERVICE_NAME: mysql

networks:
  laravel:

services:
  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      <<: [*databaseEnvironment]
    networks:
      - laravel
  app:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    ports:
      - "80:80"
    # user: "${UID}:${GID}"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      <<: [*appEnvironment]
    networks:
      - laravel
